// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvPfGstx_isMqusQbJ55rLqUtoMIppzRs',
    appId: '1:551724754459:web:8428dc061b36e0375d7abe',
    messagingSenderId: '551724754459',
    projectId: 'f-r-i-d-a-y-vlelfh',
    authDomain: 'f-r-i-d-a-y-vlelfh.firebaseapp.com',
    databaseURL: 'https://f-r-i-d-a-y-vlelfh.firebaseio.com',
    storageBucket: 'f-r-i-d-a-y-vlelfh.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvGs5AAZ-MkuJzzwKT-WJLZlQ3tx6pkE8',
    appId: '1:551724754459:android:a7f23a888b63602d5d7abe',
    messagingSenderId: '551724754459',
    projectId: 'f-r-i-d-a-y-vlelfh',
    databaseURL: 'https://f-r-i-d-a-y-vlelfh.firebaseio.com',
    storageBucket: 'f-r-i-d-a-y-vlelfh.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBMNJa91ux-7Jh0dc4GCcIi1SulkpshDo',
    appId: '1:551724754459:ios:657cae5cb7827d655d7abe',
    messagingSenderId: '551724754459',
    projectId: 'f-r-i-d-a-y-vlelfh',
    databaseURL: 'https://f-r-i-d-a-y-vlelfh.firebaseio.com',
    storageBucket: 'f-r-i-d-a-y-vlelfh.appspot.com',
    iosClientId: '551724754459-8vb5mj0fig6gnbp7jdsbsfa7t8cvt6ek.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginTrial2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBMNJa91ux-7Jh0dc4GCcIi1SulkpshDo',
    appId: '1:551724754459:ios:657cae5cb7827d655d7abe',
    messagingSenderId: '551724754459',
    projectId: 'f-r-i-d-a-y-vlelfh',
    databaseURL: 'https://f-r-i-d-a-y-vlelfh.firebaseio.com',
    storageBucket: 'f-r-i-d-a-y-vlelfh.appspot.com',
    iosClientId: '551724754459-8vb5mj0fig6gnbp7jdsbsfa7t8cvt6ek.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginTrial2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvPfGstx_isMqusQbJ55rLqUtoMIppzRs',
    appId: '1:551724754459:web:d229b641908c222b5d7abe',
    messagingSenderId: '551724754459',
    projectId: 'f-r-i-d-a-y-vlelfh',
    authDomain: 'f-r-i-d-a-y-vlelfh.firebaseapp.com',
    databaseURL: 'https://f-r-i-d-a-y-vlelfh.firebaseio.com',
    storageBucket: 'f-r-i-d-a-y-vlelfh.appspot.com',
  );
}
